id: I0A808882
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:52:10.248780
last_modified: 2023-02-09 14:52:10.248881
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: en
bases:
  D4D1:
    base_file: D4D1.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
